dist: trusty
sudo: false
language: node_js
node_js: node
addons:
  chrome: stable

install:
- npm ci
cache:
  directories:
  - $HOME/.npm
script:
- npm run lint
- npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
- npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/ngx-image-fallback
  on:
    branch: main

git:
  depth: 3

after_success:
  - npm run travis-deploy-once "npm run semantic-release"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/